export function generateICS(opportunity: {
  title: string;
  deadline: string;
  organization: string;
}) {
  const start = new Date(opportunity.deadline);
  const end = new Date(start);
  end.setHours(23, 59, 59, 999);

  const toFormat = (d: Date) =>
    d.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Opportunity Inbox Copilot//EN",
    "BEGIN:VEVENT",
    `UID:${Date.now()}-${Math.random().toString(36).slice(2)}@opp-copilot`,
    `DTSTAMP:${toFormat(new Date())}`,
    `DTSTART:${toFormat(start)}`,
    `DTEND:${toFormat(end)}`,
    `SUMMARY:📅 ${opportunity.title} (${opportunity.organization})`,
    `DESCRIPTION:Deadline for ${opportunity.title}. Generated by Opportunity Inbox Copilot.`,
    "END:VEVENT",
    "END:VCALENDAR",
  ].join("\r\n");
}

export function downloadICS(opportunity: {
  title: string;
  deadline: string;
  organization: string;
}) {
  const ics = generateICS(opportunity);
  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${opportunity.title.replace(/\s+/g, "_").slice(0, 40)}_deadline.ics`;
  a.click();
  URL.revokeObjectURL(url);
}
